defaults:
- override hydra/job_logging: colorlog
- override hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ./outputs/${now:%m-%d}/${now:%H-%M-%S}

name: conv_phase1_shaped_reward
## WANDB params
# The wandb project name
project: Lux_AI_2021
# The wandb user to log to
entity: mrzhuzhe
# The wandb group for the run
group: version1

## ENV params
act_space: BasicActionSpace
obs_space: FixedShapeContinuousObs
obs_space_kwargs: {}
reward_space: StatefulMultiReward
reward_space_kwargs:
  #early_stop: True
  #city: 2.
  #unit: 1.
  #fuel: 0.
  step: 0.005

## TRAINING params
total_steps: 2e7
num_actors: 2
n_actor_envs: 16
unroll_length: 16
batch_size: 4
discounting: 0.999

## MODEL params
model_arch: conv_model
n_blocks: 4
hidden_dim: 64
embedding_dim: 32
n_merge_layers: 1
normalize: False
sum_player_embeddings: False
use_index_select: False
rescale_value_input: True
rescale_se_input: True
# Conv-specific params
kernel_size: 5


## OPTIMIZER params
optimizer_class: Adam
optimizer_kwargs:
  lr: 1e-4
  # See https://arxiv.org/pdf/2105.05246.pdf
  eps: 0.0003
  #alpha: 0.9
min_lr_mod: 0.01

## LOSS params
entropy_cost: 0.001
baseline_cost: 1.
teacher_kl_cost: 0.
# lambda parameter for TD-lambda and UPGO losses
lmb: 0.8
reduction: sum

# MISCELLANEOUS params
actor_device: cuda:0
learner_device: cuda:0
disable_wandb: False
model_log_freq: 10
# file_descriptor or file_system
sharing_strategy: file_descriptor


load_dir: /mnt/e28833eb-0c99-4fe2-802a-09fa58d9c9f5/lust/outputs/03-03/17-38-29/
checkpoint_file: 01641984.pt