defaults:
- override hydra/job_logging: colorlog
- override hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ./outputs/${now:%m-%d}/${now:%H-%M-%S}

# Parameters to overwrite
total_steps: 9e8
#batch_size: 8
checkpoint_freq: 60.
#teacher_load_dir: /Windows/Users/isaia/Documents/GitHub/Kaggle/Lux_AI_2021/outputs/11-18/20-32-30/
#teacher_checkpoint_file: 26530944.pt

# Continue from previous run
load_dir: /Windows/Users/isaia/Documents/GitHub/Kaggle/Lux_AI_2021/outputs/11-23/00-10-13/
checkpoint_file: 0003205952.pt
weights_only: False

# Convenience for debugging
#disable_wandb: False
#debug: False